### ISSUE TITLE
Split config type

### ISSUE THREAD

**Issue by Aya0wind** [pikiwidb/pika-proxy#20]
Current config type has too many fields, we need to spilt them into different sub structs.
But we still need this type to deserialize from file and don't want to add a new field, we can use ```#[serde(flattern)```, see [serde](https://serde.rs/attr-flatten.html).
Example:
```rust
#[derive(Serialize, Deserialize, Debug, Default)]
#[serde(default)]
pub struct JodisConfig{
    jodis_name: String,
    //...
}

#[derive(Serialize, Deserialize, Debug, Default)]
#[serde(default)]
pub struct BackendConfig{
    #[serde(deserialize_with = "deserialize_string_to_duration")]
    backend_ping_period: Duration,
    //...
}
#[derive(Serialize, Deserialize, Debug, Default)]
#[serde(default)]
pub struct Config{
    #[serde(flatten)]
    jodis: JodisConfig,
    #[serde(flatten)]
    backend: BackendConfig,
}
```
this ```Config```also can be deserialized from 
```toml
jodis_name = "xxx"
backend_ping_period = "30s"
```

**Comment by Aya0wind** [comment]
pr: #21

**Comment by Dennis-Zhang-SH** [comment]
Don't we support general redis protocol transport? What's the reason of adding this Jodis config?

**Comment by Aya0wind** [comment]
> Don't we support general redis protocol transport? What's the reason of adding this Jodis config?

JodisConfig was already in config type before I wrote this pr, I just copied it here, because I'm not sure it should be remove or not. I agree with you that redis protocol can support Java client. @yaoyinnan Should we remove jodis support in our project?

**Comment by yaoyinnan** [comment]
> > Don't we support general redis protocol transport? What's the reason of adding this Jodis config?
> 
> JodisConfig was already in config type before I wrote this pr, I just copied it here, because I'm not sure it should be remove or not. I agree with you that redis protocol can support Java client. @yaoyinnan Should we remove jodis support in our project?

I describe this issue in #22, we temporarily remove Jodis because it is designed for load balancing when clients connect to Proxy.
