### ISSUE TITLE
roadmap: pika rust proxy roadmap

### ISSUE THREAD

**Issue by yaoyinnan** [pikiwidb/pika-proxy#5]
![image](https://github.com/pikiwidb/pika-proxy/assets/35447132/e314ad22-4359-4823-987d-fff676e7d8b9)

## Phase 1: Implement Redis client communication backhaul
1. Only one Redis/Pika node.
2. The loop_writer of the Session stores the user's request into a channel with a size of 1024.
3. The loop_reader of the Session directly stores the user request into the input of the backend. This process does not distinguish between slots because there is only one DB. router and forward only implement simple logic.
4. Backend, initialization, cyclically runs loop_writer to read input requests. Create loop_reader, verify config.ProductAuth, DB, and create request task. Put the request into the task.
5. The loop_reader loops through the task, gets the returned result, wakes up the loop_writer of the Session, and returns the request.
6. The loop_writer of Session returns the request to the user.

Main modules:
- proxy.rs
- request.rs
- session.rs
- backend.rs
- resp.rs

## Phase 2: Realize the message mechanism of Slot distribution
1. Multiple servers, each with multiple Redis/Pika master and slave nodes.
2. The loop_writer of the Session stores the user's request into a channel with a size of 1024.
3. The loop_reader of the Session calculates the slot through the key, and forwards the user request identification to the input of the backend of the corresponding DB through the Router and Forward.
4. Backend, initialization, cyclically runs loop_writer to read input requests. Create loop_reader, verify config.ProductAuth, DB, and create request task. Put the request into the task.
5. The loop_reader loops through the task, gets the returned result, wakes up the loop_writer of the Session, and returns the request.
6. The loop_writer of Session returns the request to the user.

Main modules:
- router.rs
- slots.rs
- proxy.rs

## Phase 3: Interact with Codis Dashboard components
1. Connect to the interface of the Codis Dashboard component.
2. Develop an API that interacts with Codis Dashboard to report Proxy status, obtain cluster topology information, etc.
3. Integrate the Proxy module into Codis to ensure that the Proxy and Dashboard can communicate normally.
4. Perform an overall integration test to verify the function and performance of the Proxy module in Codis.

Main modules:
- proxy.rs
- proxy_api.rs
- stats.rs
- metrics.rs

### Metrics

Use json, influxdb, stats to get metrics.
- metrics.rs

### Jodis

For java client connection
- jodis.rs

### Overview & Stats

ProxyAPI Get Proxy information
- proxy.rs
- proxy_api.rs
- stats.rs

## Normative best practice
1. Error handling
2. Logs
3. Generics
4. Lifetimes
5. asynchronous programming (tokio + async)

**Comment by infdahai** [comment]
Just pin this?

**Comment by yaoyinnan** [comment]
Adjust the architecture plan, subject to this: https://github.com/pikiwidb/pika-proxy/wiki/Pika-Proxy-%E6%96%B9%E6%A1%88
